"""Split models into modules

Revision ID: 95a5147aef0f
Revises: 74ba9833d132
Create Date: 2026-04-20 09:17:59.736954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a5147aef0f'
down_revision: Union[str, Sequence[str], None] = '74ba9833d132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'booking_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('complaints', 'booking_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('medical_records', 'booking_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('video_meetings', 'booking_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_meetings', 'booking_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('medical_records', 'booking_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('complaints', 'booking_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('bookings', 'booking_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
