"""Init V2 Database Schema

Revision ID: a31d1b84062f
Revises: 
Create Date: 2026-04-20 14:44:31.667642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31d1b84062f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_item_id'), 'catalog_items', ['item_id'], unique=False)
    op.alter_column('complaints', 'complaint_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_provider_availability_id'), 'provider_availability', ['id'], unique=False)
    op.alter_column('reviews', 'review_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_saved_addresses_address_id'), 'saved_addresses', ['address_id'], unique=False)
    op.drop_constraint(op.f('service_providers_email_key'), 'service_providers', type_='unique')
    op.create_index(op.f('ix_service_providers_email'), 'service_providers', ['email'], unique=True)
    op.create_index(op.f('ix_services_service_id'), 'services', ['service_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_services_service_id'), table_name='services')
    op.drop_index(op.f('ix_service_providers_email'), table_name='service_providers')
    op.create_unique_constraint(op.f('service_providers_email_key'), 'service_providers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_saved_addresses_address_id'), table_name='saved_addresses')
    op.alter_column('reviews', 'review_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_provider_availability_id'), table_name='provider_availability')
    op.alter_column('complaints', 'complaint_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_catalog_items_item_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    # ### end Alembic commands ###
