"""Add missing provider columns

Revision ID: ea609cee75c7
Revises: 
Create Date: 2026-04-15 19:40:29.949518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea609cee75c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_providers',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('background_verification', sa.String(length=50), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('license_document_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_service_providers_email'), 'service_providers', ['email'], unique=True)
    op.create_table('provider_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('time_slot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_availability_id'), 'provider_availability', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('doctor_service_id', sa.BigInteger(), nullable=True),
    sa.Column('medicine_id', sa.BigInteger(), nullable=True),
    sa.Column('lab_test_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('booking_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('order_notes', sa.Text(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_gender', sa.String(length=50), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_service_id'], ['doctor_services.service_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_test_id'], ['lab_tests.test_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('complaints',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.provider_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('medical_records',
    sa.Column('record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('video_meetings',
    sa.Column('meeting_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('host_url', sa.Text(), nullable=False),
    sa.Column('join_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('room_name')
    )
    op.drop_table('provider_services')
    op.drop_index(op.f('ix_provider_inventory_inventory_id'), table_name='provider_inventory')
    op.drop_table('provider_inventory')
    op.add_column('doctor_services', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('doctor_services', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'doctor_services', 'service_providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
    op.add_column('lab_test_offerings', sa.Column('preparation_rules', sa.Text(), nullable=True))
    op.add_column('lab_test_offerings', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('lab_test_offerings_provider_id_test_id_key'), 'lab_test_offerings', type_='unique')
    op.create_foreign_key(None, 'lab_test_offerings', 'service_providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
    op.add_column('medicines', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('pharmacy_inventory', sa.Column('custom_description', sa.Text(), nullable=True))
    op.add_column('pharmacy_inventory', sa.Column('custom_image_url', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('pharmacy_inventory_provider_id_medicine_id_key'), 'pharmacy_inventory', type_='unique')
    op.create_foreign_key(None, 'pharmacy_inventory', 'service_providers', ['provider_id'], ['provider_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_saved_addresses_address_id'), 'saved_addresses', ['address_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'profile_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_saved_addresses_address_id'), table_name='saved_addresses')
    op.drop_constraint(None, 'pharmacy_inventory', type_='foreignkey')
    op.create_unique_constraint(op.f('pharmacy_inventory_provider_id_medicine_id_key'), 'pharmacy_inventory', ['provider_id', 'medicine_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('pharmacy_inventory', 'custom_image_url')
    op.drop_column('pharmacy_inventory', 'custom_description')
    op.drop_column('medicines', 'image_url')
    op.drop_constraint(None, 'lab_test_offerings', type_='foreignkey')
    op.create_unique_constraint(op.f('lab_test_offerings_provider_id_test_id_key'), 'lab_test_offerings', ['provider_id', 'test_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('lab_test_offerings', 'image_url')
    op.drop_column('lab_test_offerings', 'preparation_rules')
    op.drop_constraint(None, 'doctor_services', type_='foreignkey')
    op.drop_column('doctor_services', 'image_url')
    op.drop_column('doctor_services', 'category')
    op.create_table('provider_inventory',
    sa.Column('inventory_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('in_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.item_id'], name=op.f('provider_inventory_item_id_fkey')),
    sa.PrimaryKeyConstraint('inventory_id', name=op.f('provider_inventory_pkey'))
    )
    op.create_index(op.f('ix_provider_inventory_inventory_id'), 'provider_inventory', ['inventory_id'], unique=False)
    op.create_table('provider_services',
    sa.Column('provider_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name=op.f('provider_services_service_id_fkey')),
    sa.PrimaryKeyConstraint('provider_id', 'service_id', name=op.f('provider_services_pkey'))
    )
    op.drop_table('video_meetings')
    op.drop_table('reviews')
    op.drop_table('medical_records')
    op.drop_table('complaints')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_provider_availability_id'), table_name='provider_availability')
    op.drop_table('provider_availability')
    op.drop_index(op.f('ix_service_providers_email'), table_name='service_providers')
    op.drop_table('service_providers')
    # ### end Alembic commands ###
